project:
  type: website


website:
  title: "Econometrics"
  navbar:
     left:
       - href: index.qmd
       - href: about.qmd
         text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
     - index.qmd
     - about.qmd

format:
  html:
    theme: sketchy  # lumen, minty
    css: styles.css
    toc: true
       